repos:
  - repo: local
    hooks:

      # Format first
      - id: ruff-format
        name: ruff-format
        entry: uvx ruff format
        stages: [pre-commit, pre-push]
        language: system
        files: \.py$
        exclude: ^(neurotechx-website/\.venv|neurotechx-website/\.ruff_cache)/

      # Lint + auto-fix
      - id: ruff
        name: ruff-linters
        entry: uvx ruff check --fix
        stages: [pre-commit, pre-push]
        language: system
        files: \.py$
        exclude: ^(neurotechx-website/\.venv|neurotechx-website/\.ruff_cache)/