#cloud-config
package_update: true
package_upgrade: true
runcmd:
  # Basic hardening (swap for 1GB instances)
  - fallocate -l 1G /swapfile || true
  - chmod 600 /swapfile
  - mkswap /swapfile || true
  - swapon /swapfile || true
  - sysctl vm.swappiness=10
  - echo '/swapfile none swap sw 0 0' >> /etc/fstab

  # Install Docker & Compose
  - apt-get update -y
  - apt-get install -y ca-certificates curl gnupg
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - chmod a+r /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" > /etc/apt/sources.list.d/docker.list
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - usermod -aG docker ubuntu

  # App folders
  - mkdir -p /opt/stack/{compose,traefik,certs,prometheus,grafana,django,web}
  - mkdir -p /opt/stack/prometheus/data
  - mkdir -p /opt/stack/grafana/{data,provisioning/datasources,provisioning/dashboards}
  - chown -R ubuntu:ubuntu /opt/stack

  # Create a systemd unit to auto-start compose (pulls files placed later)
  - bash -lc 'cat >/etc/systemd/system/stack.service <<EOF
[Unit]
Description=Docker Compose Stack
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
WorkingDirectory=/opt/stack/compose
ExecStart=/usr/bin/docker compose up -d
ExecStop=/usr/bin/docker compose down
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF'
  - systemctl daemon-reload
  - systemctl enable stack.service
  - systemctl start stack.service
